### ISSUE TITLE
[Proposal] Memo in another manner

### ISSUE THREAD

**Issue by aralroca** [reactjs/rfcs#100]
**Problem**

**memo** approach is enough understandable. However is not 100% elegant solution... Especially if you have more "wrappers" like connect, withRouter, or other HOC:

```js
export default memo(
  connect(mapStateToProps, mapDispatchToProps)(MyComponent),
)
```

**Proposal**

 I will propose to do it following components configurations as displayName, propTypes, defaultProps...

```js
MyComponent.displayName = 'NameOfMyComponent';
```

Something like:

```js
export default function MyComponent() {
/* ... */
}


MyComponent.memo  = true;
```

or

```js
export default function MyComponent() {
/* ... */
}

MyComponent.memo  = (nextProps, prevProps) => { /* ... */ };
```

**Comment by aralroca** [comment]
*Pros*:

* No more wrappers
* Import is not necessary
* Is posible to unify in the future together with class components as static atribute / method. Similar of shouldComponentUpdate, but static.

**Comment by dantman** [comment]
https://github.com/reactjs/rfcs/pull/63#issuecomment-431270919

>> What if component always stays the same, it would simply have a .shouldComponentUpdate prop, which—if not implemented—results in current behaviour.

> This introduces an extra runtime property check for every single function component, making the whole app slower and potentially causing deoptimizations. This design was considered (see "Alternatives") and rejected.

**Comment by aralroca** [comment]
I didn't imagine that this extra runtime property check can make the whole app slower. In this case, I'm going to close my proposal.

However, in the case to use **memo** in all components, this extra function call is getting the app slower, isn't it?

**Comment by TrySound** [comment]
@aralroca Yes, that's why it's recommended just in a few places to fix performance holes.

**Comment by dantman** [comment]
> However, in the case to use **memo** in all components, this extra function call is getting the app slower, isn't it?

A `TheComponent.memo` must be checked every time a `<TheComponent>` may need rendering. A `React.memo(TheComponent)` function call is only executed once per component. And if memoization itself is done with an extra function call. That function call is only executed for components that are memoized (not all components regardless of memoization). i.e. In the situation where that extra layer is supposed to improve performance.

**Comment by aralroca** [comment]
Thanks @dantman  for clarification
