### ISSUE TITLE
The best practice to avoid unnecessary re-render and batch rendering in React Hooks

### ISSUE THREAD

**Issue by wood1986** [reactjs/rfcs#102]
Two issues for this code

```
const [index, setIndex] = useState(0),
      [at, setAt] = useState(0);

handleState = () => {
  const nextIndex = evaluateIndex(window.innerWidth)
  if (nextIndex !== index) { <<<<<<<<<<<<< (1)
    setIndex(nextIndex);
  }

  const nextAt = evaluateAt(window.pageYOffset)
  if (nextAt !== at) { <<<<<<<<<<<<< (2)
    setAt(nextAt);
  }
}

useEffect(() => {
  window.addEventListener("resize", handleState);
  window.addEventListener("scroll", handleState);
  return () => {
    window.removeEventListener("resize", handleState);
    window.removeEventListener("scroll", handleState);
  }
});

```

### unnecessary re-rendering issue

The `if` statment `(1)` and `(2)` are the way that I use to avoid the unnecessary render. Yes, two state variables are fine for now. If I have 10 state variables, then I have to put 10 `if` statements to perform a pre-check before calling `setX`. If so, it will be odd. Or did I do something wrong? And what is the best practice?

### batch rendering issue

every time, I call `setX`, it will trigger the rendering immediately. for example, both `nextIndex` and `nextAt` are different from previous. The first `setIndex(nextIndex)` will trigger rendering along with the existing old `at` value because `evaluateAt` has not been executed. After the rendering is completed, it will continue to run `evaluateAt` and then `setAt`. At this moment, it will trigger rendering again with nextIndex and nextAt. The first rendering along with the existing old is not necessary. What should I do to avoid the first rendering with the old `at`? I want to batch them all. Should I change to use `useState({at: 0, index: 0})`?

**Comment by jahed** [comment]
Use the "useReducer" hook if you have a lot of state.

**Comment by j-f1** [comment]
Two things:

- state updates are asynchronous. When you call `set***`it will only rerender later on.
- Also, if the new value is `===` the old value, I’m pretty sure React won’t actually go through with the update.

**Comment by snakeUni** [comment]
![image](https://user-images.githubusercontent.com/17973020/74606953-a7374d00-510f-11ea-84a0-e30478fd3d31.png)

**Comment by j-f1** [comment]
Yep, that’s basically `===` except it treats 0 and -0 as different and NaN as equal to itself.

**Comment by theKashey** [comment]
state updates are __NOT__ asynchronous, if they are called from a _non react-controlled_ code. Like `addEventListener`.

Right  now you are more or less expected to use `ReactDOM.unstable_batchedUpdates` to handle (actually rare) situations like this.

**Comment by gaearon** [comment]
Please file questions in the React repo rather than the RFC repo.
