### ISSUE TITLE
ref methods for function components

### ISSUE THREAD

**Issue by ericvicenti** [reactjs/rfcs#103]
Next-gen React is looking great, and class components are now rarely necessary.. but components that offer ref instance methods are still stuck with classes. Here's an example class which I believe is currently impossible to convert to a function component:

```js
class MyInput extends React.Component {
  // how would 'focus' be defined if MyInput was a function?
  focus = () => {
    doSideEffect()
    this.textInput.focus()
  }
  render() {
    return (
      <TextInput
        ref={ti => { this.textInput = ti; }}
        {...this.props}
      />
    );
  }
}
```

Note: I know refs+methods aren't ideal for most use-cases, but they are a reality that prevents us from leaving behind classes in our codebase.

So, I wrote the above issue and then realized that `forwardRef` could be used for this:

```js
const MyInput = forwardRef((props, ref) => {
  const innerInput = useRef(null);
  function focus() {
    doSideEffect();
    innerInput.current && innerInput.current.focus();
  }
  ref.current = { focus };
  return <Input {...props} ref={innerInput} />;
});
```
[see runnable example](https://gist.github.com/ericvicenti/7c38478f264314605124b41cd06f720f)

At first glance, this seems to work. Is this sane? Should this be documented? Optimized? Discouraged?

**Comment by phryneas** [comment]
This is exactly solved by the example at https://reactjs.org/docs/hooks-reference.html#useref - or am I missing something here?

```
function TextInputWithFocusButton() {
  const inputEl = useRef(null);
  const onButtonClick = () => {
    // `current` points to the mounted text input element
    inputEl.current.focus();
  };
  return (
    <>
      <input ref={inputEl} type="text" />
      <button onClick={onButtonClick}>Focus the input</button>
    </>
  );
}
```

**Comment by TrySound** [comment]
@ericvicenti Yes, there is an api for that.
https://reactjs.org/docs/hooks-reference.html#useimperativehandle

**Comment by ericvicenti** [comment]
Ah, can't believe I missed this handy `useImperativeHandle` hook!
