### ISSUE TITLE
findDOMNode for function components

### ISSUE THREAD

**Issue by thysultan** [reactjs/rfcs#105]
A `ReactDOM.findDOMNode` equivalent API for function components.

Any container component that doesn't render it's own view would benefit from this addition, for example:

```js
function Foo (props) {
	useLayout(() => React.Children.node(node => element.focus()))

	return props.children
}
```

**Comment by TrySound** [comment]
Hey @thysultan There is a good pattern which allows to reuse refs and void merging logic.
```js
const elementRef = React.useRef(null);

return (
  <Popup contentRef={elementRef}>
    <div ref={elementRef}>
    </div>
  </Popup>
)
```

There is also another proposal which allows to keep refs inside the component. But it's still RFC without implementation. https://github.com/reactjs/rfcs/pull/97

**Comment by thysultan** [comment]
Yes, this is an alternative API to the one mentioned in #97. 'm not sure i understand your example though. 

The mentioned use case is when the component in question is not responsible for what it renders thus just returns `props.children` so you wouldn't be able to attach a ref in that sense.

**Comment by TrySound** [comment]
My example allows parent component pass ref to your component. It's just a bit more work for consumer.

**Comment by silverwind** [comment]
I too am looking for a way to obtain a ref to the top-level child on a component that only renders its children. With class-based components one can do

````js
class Component extends React.Component {
  componentDidMount() {
    const root = ReactDOM.findDOMNode(this);
    // `root` now refers to the top-level child and we can do a side-effect on it
  }

  render() {
    return this.props.children;
  }
}
````
Any way to do the same on a functional component without rendering useless wrappers?

**Comment by j-f1** [comment]
You could use `React.forwardRef` on the component that just renders its children, passing the ref on to the rendered child.

**Comment by silverwind** [comment]
> passing the ref on to the rendered child.

It could work via adding a `forwardRef` on the child, but my goal is to not modify the child in any way. Take [this example](https://codesandbox.io/s/zbf1n), where I try to use a render prop to obtain the child ref, but it fails because functional component's can't be given refs without `forwardRef`. It does work when one changes `<Child` to a regular DOM element like `<span` but that's also not really what I want to rely on.

Ultimately, I don't think it's possible to replicate the above `findDOMNode` approach to obtain the child ref in a functional component.

**Comment by silverwind** [comment]
One solution could be to support a `ref` property on `<Fragment>`:

````jsx
function Component({children}) {
  const ref = useRef(null);

  useEffect(() => {
    // `ref.current` now refers to the first child
  })

  return (
    <Fragment ref={ref}>
      {children}
    </Fragment>
  )
}
````
Probably should not support it on the `<>` shorthand because `<ref={ref}>` would look odd.

**Comment by j-f1** [comment]
See #97

**Comment by silverwind** [comment]
Yep exactly what I had in mind. Maybe close this issue in favor of https://github.com/reactjs/rfcs/pull/97?

**Comment by gaearon** [comment]
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.

**Comment by Runcode-China** [comment]
I have a idea:
`function Component({children}) {
  const ref = useRef(null);
  return React.cloneElement(children, { ref: useRef });
}`
