### ISSUE TITLE
@timkendrick I'm less interested in the micro performance details. What I like about hooks is how they enable you to *compose behavior* - I don't have any problem with class-based components as such (performance or otherwise) I'm just looking for a practical way to compose components and reuse behaviors and states. My main motivation is there are *clearly* initialization and rendering phases - I'd like to explore approaches that don't try to force them into a single phase.

### ISSUE THREAD

**Issue by bgnx** [reactjs/rfcs#114]
@timkendrick I'm less interested in the micro performance details. What I like about hooks is how they enable you to *compose behavior* - I don't have any problem with class-based components as such (performance or otherwise) I'm just looking for a practical way to compose components and reuse behaviors and states. My main motivation is there are *clearly* initialization and rendering phases - I'd like to explore approaches that don't try to force them into a single phase.

I don't think being "stateless" is even a goal (since there is clearly a component state, whether it's stored in a component instance or somewhere else) and I'd like to explore approaches that model that fact, rather than trying to make the API *look* functional by relying on global state, side-effects, counting calls, etc.

I like simple things, that's all :-)

_Originally posted by @mindplay-dk in https://github.com/reactjs/rfcs/pull/68#issuecomment-478529530_

**Comment by gaearon** [comment]
Tjhere
