### ISSUE TITLE
rename-unsafe-lifecycles support for JSX? 

### ISSUE THREAD

**Issue by imdevan** [reactjs/rfcs#117]
I'm trying to update my React 15 app 

I tried using this tool to update the app 
https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles

```
npx react-codemod rename-unsafe-lifecycles <path>
```

This command worked, but only affected my `.js` files... I was able to manually append the `UNSAFE_` to my `.jsx` files, but I thought it was odd that this wasn't automatic, and wonder if there was a flag I missed?

**Comment by wilomgfx** [comment]
We're you able to do it? I facing the same issue 🤔

**Comment by wilomgfx** [comment]
Made it work by doing ```--jscodeshift="--extensions=jsx"```

**Comment by krotovic** [comment]
I think this issue belongs to https://github.com/reactjs/react-codemod

**Comment by threepointone** [comment]
This is now done by default by react-codemod. Closing this issue. Lemme know if you have issues.
