### ISSUE TITLE
[Hooks] useEffect: Lazy evaluation of dependencies

### ISSUE THREAD

**Issue by Izhaki** [reactjs/rfcs#122]
# Current Behaviour 

The dependencies to `useEffect` are given as an array:

```js
useEffect(
  () => { ... }
  [deps],
);
```

So they are evaluated as soon as the hook is declared.

# Desired Behaviour 

The dependencies can also be given as a function, so these can be evaluated *after the children have been rendered*:

```js
useEffect(
  () => { ... }
  () => [deps],
);
```

# Rationale

Sometimes an effect in an ancestor is conditional on its descendants changing. Phrased alternatively, sometimes the effect dependencies of an ancestor are those of its dependents. 

But if we are to compose the descendants (via the `children` prop), the ancestor has no knowledge  of the descendants' dependencies.

# Simple Example (SVG)

*Note: This is ultra-simplified example and an ultra-specific case of a generic behaviour/mechanism.*

## Result

![image](https://user-images.githubusercontent.com/880132/64571118-b8a74c80-d35a-11e9-9a28-754ad9f7293e.png)

## Code

Essential code only, removing HOCs and props:

```js
<Hexagon>
  <Text value="Text"/>
</Hexagon>
```

## Constraints

- BBox = BoundingBox
- You can only query the DOM for the BBox of the text after it has been mounted.
- The `Hexagon`'s shape should update based on its contents.
- As previously mentioned, the `Hexagon` should not know that its `children` are `Text` - it just query the BBox of the element containing its `children`.

### Descendant notifies change 

Something like this in `Text` (an HOC really):

```js
const {onChanged} = useContext(ChangeContext);

useEffect(() => {
 onChanged()
}, [props.value]); 
```

### Ancestor being notified

Whenever a descendant fires onChange a `ref` in the ancestor is mutated:

```js
descendantsChanged.current = true;
```

How this happens is an implementation detail I can share.

The important point is that by the time we hit `useEffect` in Hexagon, it has the knowledge one of its descendants has changed. It will then query the content bbox, and trigger an update, say by calling `setState`.

### The missing link

Issue is, this won't work:

```js
useEffect(
  () => { /* query children bbox here */ }
  [descendantsChanged.current],
);
```

Whereas this will (I guess):
```js
useEffect(
  () => { /* query children bbox here */ }
  () => [descendantsChanged.current],
);
```

# Complex example (HTML)

When the text of a port (eg, `out`) changes, the box of the 'chip' has to be queried:

![image](https://user-images.githubusercontent.com/880132/64572456-4dac4480-d35f-11e9-8512-19f86fb752f9.png)

**Comment by xiel** [comment]
Hey @Izhaki ,

Probably some misunderstandings here, but you should already be able to safely access/measure the children of your component within useEffect.

If you want to notify a parent manually after a (or each) re-render, just pass down a callback from the parent to the child and call it, when you want to notify the parent from within a useEffect in the child (Text) component.

Mutating ref objects like you did in your "Solution" will never trigger effects by design.

Hope that helps, otherwise a (non)-working codesandbox demo would be nice.

**Comment by Izhaki** [comment]
As I was writing a long reply, I got what you're saying. Yes, mutating isn't going to help here (unless we mutate some counter, but that is hardly an elegant solution).

I'm going to close this. But will leave you with the actual code I'm having trouble with. This is in the ancestor (HOC):

```js
  useEffect(() => {
    // We should only do this if the descendants have changed.
    const resolvedContentBox = queryBox({ ref: contentRef });
    setContentBox(resolvedContentBox);

    // We should do this if border, padding or the descendants have changed.
    const resolvedOuterBox = getOuterBox(resolvedContentBox, border, padding);
    onBox(id, resolvedOuterBox);
  }, [/* ? */]); 
```

As you can see, I've got 3 dependencies:
- padding
- border
- descendants have changed

So I can't really use deps here. Seems like I just have to run the effect on each render and put the conditionals inside.
