### ISSUE TITLE
[Proposal] useEffect with mounted state argument

### ISSUE THREAD

**Issue by yanickrochon** [reactjs/rfcs#140]
At this moment, a component like

```js
const Foo = ({ name }) => {
  const context  = useContext(GlobalContext);
  useEffect(() => {
    globalContext.setMounted(name, true);
    return () => globalContext.setMounted(name, false);
  }, [barFlag, context]);

  return (<div>foo</div>);
}
```

will call `globalContext.setMounted` twice at each and every refresh, then one last time when the component is finally unmounted.

Using a `Component` as a class, we have `componentDidMount` and `componentWillUnmount`, but no equivalent for functional component; `useEffect` does not tell if the cleanup function is executed one last time.

I would propose having one argument passed to the cleanup function, indicating whether or not the component is still mounted (or will unmount). Such as

```js
const Foo = ({ name }) => {
  const context  = useContext(GlobalContext);
  useEffect(() => {
    globalContext.setMounted(name, true);
    return willUnmount => willUnmount && globalContext.setMounted(name, false);
  }, [barFlag, context]);

  return (<div>foo</div>);
}
```

In that case, every refresh will not call `globalContext.setMounted(name, false);` except when the component will no longer update.

**Comment by j-f1** [comment]
Why couldn’t you do

```js
useEffect(() =>
  globalContext.setMounted(name, true);
  return () => globalContext.setMounted(name, false);
  }, [name]);
```

which won’t be run again until `name` is changed?

**Comment by yanickrochon** [comment]
Because if I need to notify a context only when a component is unmounting, currently, I have to pass by the parent component; the functional component has no idea when it's not being mounted. So the cleanup function, in the example you listed, will run regardless if the component is still mounted or not. The idea is to cleanup whenever the component is unmounted only.

For example, the documentation speaks of `componentDidMount` with 

```js
useEffect(() => {}, []);
```

it speaks of `componentDidUpdate` with

```js
useEffect(() => {});
```

but the use case `componentWillUnmount` is impossible to reproduce with a functional component.

**Comment by phryneas** [comment]
`componentDidUnmount` is easily reproducable by

```ts
useEffect(function (){
  return function cleanupOnUnmount(){
    console.log("goodbye");
  }
}, []);
```

`componentWillUnmount` is deprecated for class components as well and will not work in concurrent mode.

**Comment by sag1v** [comment]
I think its kind of related to #187

**Comment by gaearon** [comment]
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.
