### ISSUE TITLE
useMount

### ISSUE THREAD

**Issue by kitten-s** [reactjs/rfcs#143]
It will cool to add useMount hook that behaves as oncomponentdidmount. Because it is more simple to read than useEffect(fn, []);

**Comment by sandiiarov** [comment]
You can build it on your own.

```js
function useMount(mount) {
  React.useEffect(mount, []);
}
```

**Comment by 3imed-jaberi** [comment]
@kitten-s , you can use [this npm pkg (use-lifecycle-hooks)](https://www.npmjs.com/package/use-lifecycle-hooks), if this approach it's more comfortable for you.

**Comment by gaearon** [comment]
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.
