### ISSUE TITLE
Can we unify components and containers?

### ISSUE THREAD

**Issue by zzz6519003** [reactjs/rfcs#151]

**Comment by phryneas** [comment]
What exactly is your context here?

The whole React docs have only one notion of "containers" other that the DOM node that is used for mounting, and that on the HOC documentation (where it kind of makes sense to use that word).

Other than that, this is more of a react-redux thing and if you are relating to those, you should take that discussion there. But as far as I know they aren't really pushing that concept any more.

**Comment by gaearon** [comment]
React doesn’t have a concept of containers.
