### ISSUE TITLE
Rewrite the react.js tutorial page with hooks

### ISSUE THREAD

**Issue by DaniAkash** [reactjs/rfcs#153]
It's been well over a year since hooks were introduced & almost all examples of React Native documentation have been rewritten with hooks. However the official [react tutorial](https://reactjs.org/tutorial/tutorial.html) still uses the traditional class components. 

Is there any plans to replace the tutorial with new hooks based components? or if it hasn't been planned yet, I'd be happy to pick it up

**Comment by DaniAkash** [comment]
Have rewritten the whole tutorial. Now just gotta find the steps to merge it...

**Comment by gaearon** [comment]
Please see https://github.com/reactjs/reactjs.org/issues/3308.
