### ISSUE TITLE
[Feature Request] [hooks] input#value bindings with useState

### ISSUE THREAD

**Issue by tomitheninja** [reactjs/rfcs#156]
*From https://github.com/facebook/react/issues/18611 including dmytro-lymarenko's ideas*

## Summary
Many of the popular JavaScript frameworks support binding value to a HTMLInputElement

The purpose of value binding is to eliminate the need both the value and the onchange property.

I think, with the new useState syntax, it became possible to implement this in react with a nice syntax and no breaking changes.

## Detailed design
```TypeScript
function MyComponent() {
  const bind = useState('')
  const [value, setValue] = bind
  return (
    <input bind={bind} />
    // ...
  )
}
```

## Alternatives
By introducing a new hook.
In my opinion, this is easier to learn.

```TypeScript
const [value, bind] = useStateBind('')
<p>{value}</p>
<input bind={bind} />
```

**Comment by jquense** [comment]
What is the benefit of not passing the value? Seems like your introduce API complexity and possible confusion to save a very minimal amount of typing. You could always do something like this yourself with a custom hook

```js
const useBinding = (defaultValue) => {
  const [value, onChange] = useState(defaultValue)

  return { value, onChange }
}

// ...

const bind = useBinding('')
<p>{bind.value}</p>
<input {...bind} />
```

**Comment by tomitheninja** [comment]
Almost every website has some sort of forms. By using a bind, the code will be cleaner and more failsafe.
And I think that this is not that confusing, and it takes seconds to learn it.

**Comment by kingdaro** [comment]
But with jquence's suggestion to make a custom hook, you're not going to be writing that. You'll be writing this:
```ts
<input type="text" placeholder="Hello World" {...bind} />
```
...which actually happens to be shorter than the proposed syntax, without introducing new API or new concepts

**Comment by MaxmaxmaximusGitHub** [comment]
api implies low-level things, what you offer ALREADY can be described by the available api.

**Comment by sergeysibara** [comment]
It would be great if exist an small standard library with a set of the most necessary hooks.
It’s bad when there is no standard, and everyone implements by himself such commonly used things as two way binding.

**Comment by gaearon** [comment]
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.
