### ISSUE TITLE
Suspend promise batch?

### ISSUE THREAD

**Issue by achung89** [reactjs/rfcs#157]
I've encountered a use case where it might be useful to read from a resource from map callback

```javascript
const arr2 = arr1.map( val => {
  resource.read(val.prop);
})
```

If I understand suspense correctly, each invocation to `.read` will throw and resolve one by one. Could we  have a mechanism to throw an array of promises for parallelization?

```javascript
const parallelMap = (arr, fn) => {
  const promises = [];
  const newArray = [];
  for ( let i = 0; i < arr.length; arr++) {
    try {
      newArray.push(fn(arr[i]))
    } catch (err) {
      if(typeof err.then === 'function') {
        promises.push(err);
       continue;
      }
      throw err
    }
  }
  if (promises.length > 0) {
    throw promises // can we have this plz?
  }
  return newArr;
}

...
let arr2 = parallelMap(arr1,  val => {
  resource.read(val.prop)
})
```

**Comment by j-f1** [comment]
`throw Promise.all(promises)`?

**Comment by achung89** [comment]
I think that work for my use case. thanks!

**Comment by gaearon** [comment]
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.
