### ISSUE TITLE
useRef for creation of objects?

### ISSUE THREAD

**Issue by vikr01** [reactjs/rfcs#160]
I've been seeing a common pattern of creating an object that is an instance of a class in a `useRef` call:

```javascript
const mapRef = useRef(new Map());
```

Can we maybe come up with a version of `useRef` that works a bit similarly to `useMemo`, but that it only executes the function the first time?:

```javascript
const mapRef = useCreationRef(()=>new Map());
```

[Looking at this comparatively on jsperf](https://jsperf.com/creating-a-function-vs-creating-a-map), it seems quite clear that the second version would always be faster when it involves creation of class objects. Especially when considering custom class objects, which could have constructors that do a lot more than just initialization.

If it's welcome, I'm happy to put up a PR for this.

**Comment by theKashey** [comment]
why you could not _store_ data in the state?
why you could not _transfer_ data from the state?
```js
 useRef(useState(() => new Map())[0]);
```

**Comment by vikr01** [comment]
> why you could not _store_ data in the state?
> why you could not _transfer_ data from the state?
> 
> ```js
>  useRef(useState(() => new Map())[0]);
> ```

I didn't say I did it, so I'm not sure why you're asking me. There's a *ton* of cases I'm seeing like this at Facebook.

Looks like Dan already gave an answer like this on a similar thread https://github.com/facebook/react/issues/14490#issuecomment-454990990.
