### ISSUE TITLE
[Feature request]: Add a lint rule to check overuse of hooks

### ISSUE THREAD

**Issue by otakustay** [reactjs/rfcs#163]
In some (or most) of our projects I see constantly overuse of hooks, some hooks is simply a function without any use of other hooks like:

```js
const useXSS = value => {
  return xss(value);
};
```

Not even a `useMemo` is introduced in the body of hook.

To eliminate these bad cases and to setup a clearer concept of when and how to use hooks, I'd like to recommend `eslint-plugin-react-hooks` to provide a new rule warning a hook not using any other (custom and built-in) hooks.

I may implement this and create a PR if this is acceptable in `eslint-plugin-react-hooks`.

**Comment by xiel** [comment]
Where do you see the harm in having a named like useXyz for a function?

I think it is showing the intention of the writer, that this function might want to use hooks in the future and can be considered an implementation detail, which might change over time.

**Comment by otakustay** [comment]
When I talk these cases to their authors, I found it mostly comes from misunderstand of hooks, thus I think warning them about overuse of hooks can help to establish a more clearer concept of what actually hooks are and which problems they actually solve.

I believe a function can change from hook to non-hook over time, however a consistent naming convention have more benefit on the readability and maintainability on code.

Also, hooks are infectious, by which I mean a function invoking a hook must be a hook, a incorrectly used name can results in more incorrectly named functions.

**Comment by gaearon** [comment]
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.
