### ISSUE TITLE
[Feature request] Allowing multiple refs on same DOM element

### ISSUE THREAD

**Issue by illuminist** [reactjs/rfcs#164]
## Context

I'm working on an app which need to make use of 3rd-party lib. But problem came when the lib need a ref access to DOM element and I also have ref that need to assign to the same DOM element.

So it comes down to I have 2 ref objects that need to be assigns into the same element.

## Proposal

Make ref prop to accept an array of ref object or call back.

Which should have a signature like
```jsx
{
  ref: 
    | ((el: Element| null) => void)
    | React.RefObject<Element> 
    | (((el: Element| null) => void) | React.RefObject<Element>)[]
}

**Comment by leodr** [comment]
This is possible already and it is not too difficult, as you can see [here](https://github.com/gregberge/react-merge-refs/blob/master/src/index.js).

**Comment by illuminist** [comment]
@leodr That's what I'm doing as workaround. It should be more convenience if add the feature to react directly.

**Comment by phryneas** [comment]
@illuminist that would be 227 extra Bytes that only a very small part of Reacts users ever needed - for something that is easily implementable in userspace. That stuff adds up pretty fast.

**Comment by theKashey** [comment]
Just don't forget to maintain req equality on the derived ref. It might not work that great out of the box - https://github.com/gregberge/react-merge-refs/issues/5

**Comment by gaearon** [comment]
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.
