### ISSUE TITLE
[Feature Request] Support a special "cancellation" `throw` inside useEffect

### ISSUE THREAD

**Issue by natew** [reactjs/rfcs#173]
Simple as that, could see it like this:

```tsx
import { useEffect, CancellationError } from 'react'

const App = () => {

  useEffect(() => {
     throw new CancellationError('Valid cancellation')
  }, [])

  return null
}
```

This would then *not* propagate the error, and it would also allow you to see the cancellations using a debug flag or in the React devtools.

Upside would be allowing the common `invariant` or `assert` pattern inside effects, which would make for much nicer early-returns that include messages for debugging exactly why an effect returned early.

Perhaps this exists already internally?

**Comment by gaearon** [comment]
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.
