### ISSUE TITLE
the ability to check if something is function or class or an arrow function

### ISSUE THREAD

**Issue by wentout** [reactjs/rfcs#178]
Hi, folks )

In a relation to document [**0000-create-element-changes.md**](https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#deprecate-module-pattern-components), seems it would be nice to have an ability to check if something is **class** or **function** or an **arrow function**, that quotation:

> The important goal here is that if we're going to introduce different semantics between classes and function components, we need to know before calling them which semantics we're going to apply.

As far as we know there might be some sort of confusion to implement this checks. But, indeed, it is possible in runtime with no usage of `.toString()` serialization. The short example of what does it mean to implement `isClass(fn)`: 

```javascript
const isClass = (fn) => {
	if (typeof fn !== 'function') {
		return false;
	}
	if (typeof fn.prototype !== 'object') {
		return false;
	}
	if (fn.prototype.constructor !== fn) {
		return false;
	}
	return Object.getOwnPropertyDescriptor(fn, 'prototype').writable === false;
};
```

And the last line for **isFunction** would end with `true` keyword. This means there is strict difference between functions and classes, which might be tracked. The gist with full sum of checks is here: [**gist_link**](https://gist.github.com/wentout/ea3afe9c822a6b6ef32f9e4f3e98b1ba).

Actualy my colleague @zeroWheel being active React developer asked me to start this issue. And we don't know if it is useful.

The last thing I'd wish to add is about known buggy behaviour of Babel.js: there is no difference between class, function or arrow function after transpilation. So, seems it might be some sort of unpredictable behaviour. Full checks are here: [**babel_buggy_behaviour**](https://github.com/denis-churbanov/babel-bug) thanks for @denis-churbanov.

This Babel behaviour comes from ancient times, when there were no classes or arrow functions. They use corejs, and it might look not so bad, but it might be strange with configuring: I'm unable to figure out with proper config of polyfilling.

And absolutely the same is TypeScript behaviour if targeting below ES2015.

Hope this information might help somehow.

**Comment by eps1lon** [comment]
https://overreacted.io/how-does-react-tell-a-class-from-a-function/ allows checking this. I think this is somewhat considered a public API. I couldn't find any rationale why React users should be able to do this check. The quote is written from the perspective of React internals.

> The last thing I'd wish to add is about known buggy behaviour of Babel.js: there is no difference between class, function or arrow function after transpilation.

`class` is just syntactic sugar. Even without transpilation there's no 100% accurate way to determine if something is a class or a function.

With regards to function vs arrow function: Why should this matter? You can't distinguish that with you babel setup because you probably transpile for a target that doesn't support arrow functions.

**Comment by wentout** [comment]
## 0.

### Thank you for the answer @eps1lon!

The link to [**how-does-react-tell-a-class-from-a-function**](https://overreacted.io/how-does-react-tell-a-class-from-a-function/) is wonderful!
**And that article is an answer to the issue!** Thank you again!

There was no arguing against or for something. **We were just seeking** is this usefull or not, and if it might be helpful somehow, maybe, probably. And  article clearly:

1. points to `.prototype` property descriptor for class: [`writeable` === false](https://stackoverflow.com/a/29094018/6931257);
2. refers to known stuff about babel transpilation: [they are not going to give any solution](https://github.com/facebook/react/issues/4599#issuecomment-136562930);
3. explains why `isReactComponent` matters: [the article itself](https://overreacted.io/how-does-react-tell-a-class-from-a-function/).

---

### In a relation to the other mentioned questions :

---

### 1.

> rationale why React users should be able to do this check

We was wondering to profide useful information for core. And now seems it is useless, as it is something well known. Just because it was written there, inside of  [**0000-create-element-changes#deprecate-module-pattern-components**](https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#deprecate-module-pattern-components)

> The important goal here is that if we're going to introduce different semantics between classes and function components, we need to know before calling them which semantics we're going to apply.

, and we thought it is some sort of thing that is hard to get into.

So, finally, there is nothing to help with, it is as it is just because )

---

### 2. 

> class is just syntactic sugar. Even without transpilation there's no 100% accurate way to determine if something is a class or a function.

Class works like sugar, yes. And it is a bit tricky to implement classes using no class keyword, especially the extends part:  

- We might be dealing with functions as classes. We might prohibit them without `new` keyword, using `new.target`. But new.target itself is slightly new feature.
- And as `.getPrototypeOf` of extended class refers to the base class, the other part is that `.prototype` property itself is not re-writeable for classes. Though again: it is new syntax improvements from ES2015. So it might be overcomplicated journey with Object.setPrototypeOf and Object.defineProperty and 'use strict'; even having ES2015 as starting point.
- And also before and after there is necessity to deal with `MyClass.prototype.constructor` properly. And even after that there are some misconfigurations and other details with private fields and mixins. And so far does it worth getting so deeply inside?

Might be that is why it seems like it is syntactic sugar, because transpilation does not follow each and every part of the spec. And even if it seems they are syntax sugar, there are other parts of class constructor [for example]((https://medium.com/@arunrajeevan/class-is-not-just-a-syntactic-sugar-in-javascript-e0a28444263b)). So class keyword is not useless. But in a relation of how infrastructure of transpilation works they are not so usefull, yes.

---

### 3. 

> With regards to function vs arrow function: Why should this matter? You can't distinguish that with you babel setup because you probably transpile for a target that doesn't support arrow functions.

Yes, yes, the same, it is fully described with information provided by the article.

---

Just because seems everything works being transpiled to function )

## Good Luck ! )

**Comment by wentout** [comment]
Just in case it might worth something, there is a way to fix:

### for Arrow Functions

```javascript
const workingArrow = () => {};
// right after arrow function definition
Object.defineProperty(workingArrow, 'prototype', {
    value: undefined
});
```

### for Classes

```javascript
class WorkingClass {}
// right after class definition
Object.defineProperty(WorkingClass, 'prototype', {
    writable: false
});
```

**Comment by wentout** [comment]
I tried to prepare PR for babel https://github.com/babel/babel/pull/12115

**Comment by gaearon** [comment]
If you have comments for that RFC, please leave it on the RFC.
