### ISSUE TITLE
npx-create-react-app creating a folder tempnodejsnpm

### ISSUE THREAD

**Issue by mannawar** [reactjs/rfcs#180]
Hello:

When i do npx create-react app a temporary folder is being always created. I have raised this issue here as well. Link is here https://github.com/facebook/create-react-app/issues/9743
I am sorry for reposting it here.

Thanks,

**Comment by mannawar** [comment]
If anybody has solution to my problem, then please post here. Certainly, I will find that out. And sure disliking my issue will not help.
Thanks again

**Comment by phryneas** [comment]
This is the RFC section of React, where people post formal suggestions for new React features and discuss those. Hundreds of people are sent a copy of every post here.

It has nothing to do with create-react app. Your other issue is at the right place, but here is certainly the wrong place for this.
