### ISSUE TITLE
useIf: Conditional hooks

### ISSUE THREAD

**Issue by adrianhelvik** [reactjs/rfcs#184]
This is an example from our codebase. The hook in question (`usePrevAnswer`) triggers an API call. When `props.preview` is truthy we do not want this to happen. To solve this I had to create two extra outer components.

```javascript
export default function withPrevAnswer(templateName) {
  return Component => {
    const WithPrevAnswerPreview = props => {
      return <Component {...props} />
    }

    const WithPrevAnswerNonPreview = props => {
      const prevAnswer = usePrevAnswer(templateName)

      return <Component {...props} prevAnswer={prevAnswer} />
    }

    const WithPrevAnswer = props => {
      if (props.preview) {
        return <WithPrevAnswerPreview {...props} />
      }
      return <WithPrevAnswerNonPreview {...props} />
    }

    hoist(WithPrevAnswer, Component)

    return WithPrevAnswer
  }
}
```

With `useIf`, I would be able to express this way more succinctly:

```javascript
export default function withPrevAnswer(templateName) {
  return Component => {
    const WithPrevAnswer = props => {
      const prevAnswer = useIf(!props.preview, () => usePrevAnswer(templateName))

      return <Component {...props} prevAnswer={prevAnswer} />
    }

    hoist(WithPrevAnswer, Component)

    return WithPrevAnswer
  }
}
```

This code had originally purposefully broken the rules of hooks to conditionally call the usePrevAnswer. I don't think I am the only one who has purposefully broken the rules of hooks for simplicity. In this example, a preview view would never be converted to a live view and vice versa.

With `useIf`, Eslint could simply instruct you to wrap conditional hooks. This would simplify refactoring and make it easier to do The Right Thing™ by default.

**Comment by gaearon** [comment]
Why not call it unconditionally but use the result conditionally?

**Comment by adrianhelvik** [comment]
Because custom hooks may trigger unwanted side effects. In this case an API request to a mocked resource would have been made.

**Comment by dantman** [comment]
Every respectable API hook I've used comes with a way to skip API calls based on a condition.

**Comment by adrianhelvik** [comment]
This hook would remove the need for all skip conditions and simplify usage for new developers. `useIf` is a better name though.

**Comment by MHA15** [comment]
maybe usePrevAnswer should get condition and skip sideEffects inside itself

**Comment by gaearon** [comment]
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.
