### ISSUE TITLE
Improve profiling react applications

### ISSUE THREAD

**Issue by chakrihacker** [reactjs/rfcs#187]
The `Profiler`component does a great job of providing insights. Recently I read this [blog post](https://blog.coinbase.com/optimizing-react-native-7e7bf7ac3a34) from coinbase about optimizing performance in react native. They have created a babel plugin which adds a profiler component to every file and aggregates those results. It would be nice if react has a toggle kind of functionality to add profiler to all components, so that measuring and understanding would be easier.

P.S: This is my first RFC. I would be happy to help in providing more details. 

Thanks

**Comment by gaearon** [comment]
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.
