### ISSUE TITLE
Static Lifecycle Methods’ getDerivedStateFromProps access to previous props

### ISSUE THREAD

**Issue by acusti** [reactjs/rfcs#19]
While reading [0006-static-lifecycle-methods.md](https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md#static-getderivedstatefrompropsnextprops-props-prevstate-state-partialstate--null), I noticed this note in the detailed design for `static getDerivedStateFromProps`:

> Note that React may call this method even if the props have not changed. If calculating derived data is expensive, compare next and previous props to conditionally handle changes.

@bvaughn With `getDerivedStateFromProps` being a static method and not receiving `prevProps` as an argument, how would this be accomplished?

The [example](https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md#state-derived-from-propsstate) illustrating use of this pattern notes that “if the calculation is fast enough it could just be done in `render`”, so I’m guessing that the primary motivation for using `getDerivedStateFromProps` should be more expensive calculations. But I also saw the [discussion](https://github.com/reactjs/rfcs/pull/6/files#r156702078) about the `static deriveStateFromProps(props, state, prevProps) {` proposal, which suggests that this kind of a check won’t be possible.

An aside: as a React consumer, I would expect static `get**` component methods to be there as something I would invoke for use in my component, rather than something I would provide for the library’s use. Though `deriveStateFromProps` would still require a doc lookup for most developers, it does look less like something I would confuse with my own component properties or methods.

I’m posting this as an issue because I cannot comment in the original PR and because it seems there is an issue that needs to be resolved one way or another with the text of the RFC. I hope this is the right way to go about this!

**Comment by bvaughn** [comment]
The RFC proposal shows [an example of how to do this](https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md#state-derived-from-propsstate), and it was discussed a couple of times throughout the comment thread (eg [here](https://github.com/reactjs/rfcs/pull/6#discussion_r162865372)).

**Comment by acusti** [comment]
Missed that part of the conversation, sorry about that. As its stands, the language is definitely confusing (for those trying to suss out best practice), but now I understand what it means.

**Comment by bvaughn** [comment]
I don't think the language of the RFC is super important at this point. I think the release blog post and updated documentation (which I'm working on this week) are what matters, because that's where most people will learn about the API changes. 😄

**Comment by marsonmao** [comment]
Could `prevProps` just being the same value as 'nextProps' for the initial render? In that way, prev won't be nullable, prev and next could always be comparable, and the initial state deriving should be fine as well. (P.S. not sure if this is the correct thread to respond though...)

**Comment by TrySound** [comment]
@marsonmao Nope. It was discussed a lot of times. https://github.com/reactjs/rfcs/pull/40

**Comment by marsonmao** [comment]
@TrySound Thanks for the link! I'll move to that thread.

**Comment by bvaughn** [comment]
This may also be worth a quick read, if you haven't seen it yet 😄

https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

**Comment by abedmurrar** [comment]
what i did was
in the constructor of my component, i did
```js
constructer(props){
super(props);
this.state={
//stuff
};
ClassName.getDerivedStateFromProps = ClassName.getDerivedStateFromProps.bind(this);
}
```
then in the `getDerivedStateFromProps` function i accessed the prevProps using
```js
static getDerivedStateFromProps(nextProps, prevState){
if(this.props.something !== nextProps.something){
// do something
}
}
```

**Comment by TrySound** [comment]
@abedmurrar Sure, you can, but you shouldn't do this or your app will eventually be broken.

**Comment by j-f1** [comment]
@abedmurrar This also won’t work if there’s more than one instance of the component. In that case, `this.props` will reference one instance’s props and `nextProps` another’s.
