### ISSUE TITLE
[React Server Components] Idea to simplify overall design

### ISSUE THREAD

**Issue by brillout** [reactjs/rfcs#191]
The restriction that Client Components aren't allowed to import Server Components is the source of complexities. I'm guessing the purpose of this restriction is to avoid the waterfall situation of rendering going back-and-forth between client and server. Is that the main reason for the restriction?

AFAICT removing this restriction would considerably simplify the usage of Server Components, and I'm wondering if removing this restriction is possible, in a performant way:
 - When the server renders a Server Component, all descendants of the Server Component are rendered on the server-side, including all descendant Client Components. (In order to avoid rendering going back-and-forth between client-side and server-side.) Once the virtual dom computing goes server-side it never goes back client-side.
 - Whenever the client-side wants to render a Server Component, the client calls an endpoint `/_react/render` and the server computes and returns the virtual dom and the list of context objects used. The client passes the context objects and the state of all the Server Element's descendant Client Elements so that the server has all the information needed to be able to compute the virtual dom. The client then uses the returned virtual dom to perform reconciliation, and uses the list of used context to know whether to request a re-render whenever a context object changes.
 - When a Client Component is rendered by the server, the server only computes the virtual dom while the hydration on the client-side takes care of running the Client Component's `useEffect` & co. Similarly to what is being done today with SSR where Client Components are allowed to run on the server but hydration takes care of the client-side stuff.
 - The webpack react plugin removes the server component source code from the client-side bundle.

AFAICT this should work, or am I missing something here?

The benefits would be many, amongst others:
 - No routing needed. (Routing can be done simply by having a stateful Client Component orchestrating Server Components.)
 - No central caching `unstable_getCacheForType` and `unstable_useCacheRefresh` needed.
 - The client-side can cache the rendering of Server Components by using `shouldComponentUpdate`/`memo`, preventing unnecessary network round trips.
 - More things can be moved to the server. For example, the note preview (and its included heavy markdown dependency) in the left side panel of the demo can't easily be moved to the server with the current design, but, with the proposed design, this would be trivial.
 - The `/_react/render` is the only Server Components endpoint needed.
 - Migration is easier: add a) the react webpack plugin, and b) the `/_react/render` endpoint &mdash; that's it. Current React 16.x apps work as before and Server Components can be progressively added without changing the app's architecture.

The main and overarching benefit being that I can create components that are concerned only about themselves: no shared infrastructure (no `X-Location`, no `unstable_getCacheForType`, etc.), I can use Server Components wherever I want, and I can write them independently of the rest of the app. When I enter the world of a component I can think locally, whereas the restriction that Client Components aren't allowed to import Server Components forces me to think globally.

Also, this would make it possible to use Server Components without a framework.

What do you think?

I really like Server Components, and if we can simplify its usage it could become quite a perfect thing.

**Comment by davidbarratt** [comment]
> The restriction that Client Components aren't allowed to import Server Components is the source of complexities. 

Do you mean _import_ or _render_?

**Comment by davidbarratt** [comment]
I think you may be conflating Server-Side Rendering (SSR) and Server Components. The former can render client components, the latter cannot. Either can import client components.

**Comment by brillout** [comment]
@davidbarratt 

Have look at https://github.com/josephsavona/rfcs/blob/server-components/text/0000-server-components.md#capabilities--constraints-of-server-and-client-components

> Client Components [...] may not import Server Components

**Comment by davidbarratt** [comment]
> @davidbarratt
> Have look at https://github.com/josephsavona/rfcs/blob/server-components/text/0000-server-components.md#capabilities--constraints-of-server-and-client-components

Oh right, I'm sorry I read what you wrote backwards. Yes the RFC makes sense to me. A client component couldn't import a server compoment because a server component could import Node's `fs` module (as an example). If that is the case, then how would you expect the client to handle that import?

**Comment by brillout** [comment]
Let me elaborate with what I mean with:

> - The webpack react plugin removes the server component source code from the client-side bundle.

Concretely the webpack react plugin would replace the entire source code of a Server Component with the client-side mechanism that calls the `/_react/render` endpoint. (More precisely with a call to that mechanism with as argument the ID of the Server Component.)

**Comment by davidbarratt** [comment]
Isn't that what _shared_ components are? Basically the `io` libraries have both a server-side and client-side mechanism within them.

**Comment by josephsavona** [comment]
@brillout Thanks for taking the time to share your thoughts. I’d like to reply, but we’d like to keep the discussion about Server Components focused in a single place. Could you please move this post to a comment on the main RFC, please? That way people can find the answer more easily wo following two separate threads. Thanks!

**Comment by brillout** [comment]
@josephsavona done. I'm super looking forward to read your reply!

**Comment by brillout** [comment]
@davidbarratt 

A central piece of the proposal is

 >  Once the virtual dom computing goes server-side it never goes back client-side.

For that, the server should be able to compute the virtual dom of *all* components, including the Client Components. The current design prohibits Client Components from running/rendering in the server.

Shared Components are not the solution either as they are prohabited to have state and side-effects.

**Comment by davidbarratt** [comment]
> For that, the server should be able to compute the virtual dom of _all_ components, including the Client Components. The current design prohibits Client Components from running/rendering in the server.

That is Server Side Rendering (SSR). If the client has already loaded the application, why would it need to render on the server? That wouldn't be effecient.

> Shared Components are not the solution either as they are prohabited to have state and side-effects.

Right because you can't have state nor side-effects on the server...

**Comment by gaearon** [comment]
Responded in https://github.com/reactjs/rfcs/pull/188#issuecomment-753505681
