### ISSUE TITLE
psql: could not connect to server: No such file or directory

### ISSUE THREAD

**Issue by devendrabohre** [reactjs/rfcs#192]
facing problem in connceting database,
1- firstly when i clone https://github.com/reactjs/server-components-demo
and run npm install after this run npm start
![image](https://user-images.githubusercontent.com/25605831/103748262-d7d6ec80-5029-11eb-92a7-1db3102f2dfe.png)
2- second when I am trying to connect database and run 
psql postgres
comes an error
The program 'psql' is currently not installed. You can install it by typing:
sudo apt install postgresql-client-common

so I run suggested command sudo apt install postgresql-client-common
after this again an error comes
Error: You must install at least one postgresql-client-<version> package.
then I run sudo apt-get install postgresql-client
now comes an error
![image](https://user-images.githubusercontent.com/25605831/103749671-cd1d5700-502b-11eb-8208-1d1709e5c08b.png)

So Can you please tell me How I run this demo successfully on my local, Because I love this server component concept
Kudos React Team

**Comment by RusinovAnton** [comment]
This kind of question is not relevant for this repo. 
You have to figure out how to install, start, and run the Postgresql server. while this repo is meant for RFC process to discuss new features ideas for React.js. More details in the [README](https://github.com/reactjs/rfcs#react-rfcs)

Please look at specialized resources like StackOverflow to find an answer to your question. Good luck!

**Comment by gaearon** [comment]
Please file this in the demo repository.
