### ISSUE TITLE
[Question] The new JSX transform

### ISSUE THREAD

**Issue by pjstirling** [reactjs/rfcs#193]
I transpile to js, (from [parenscript](https://common-lisp.net/project/parenscript/) if you care) and there I use a transform into `React.createElement` which makes me interested in the new transform in React 17 (mentioned [here](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)).

That, in turn, links to [a file not in master](https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#detailed-design), but that file is written in the form of a proposal, and it's not clear whether it represents the final details.

Is there another document with the details?

**Comment by rickhanlonii** [comment]
Hey @pjstirling, thanks for submitting the question.

This repo isn't the right place for these type of questions, but here's the information I think you're looking for. Most of the discussion on this is in the [RFC](https://github.com/reactjs/rfcs/pull/107). The implementation of the new JSX functions are available [here](https://github.com/facebook/react/blob/master/packages/react/jsx-runtime.js). You also probably want to reference the Babel plugin that transforms JS, which is [here](https://github.com/babel/babel/blob/main/packages/babel-plugin-transform-react-jsx/src/create-plugin.js).
