### ISSUE TITLE
New React 16 Context - Nesting and overrides

### ISSUE THREAD

**Issue by jackgeek** [reactjs/rfcs#36]
I use the old context in my metadata driven application.  The metadata determines the structure of the component hierarchy.  A common usage is to provide a child component information from a container that may be n levels above the child.  It's possible that the child is not contained within a container.  Also it is possible there are multiple levels of nested containers.  

One example of nested context calls and overrides is when a unique identifier needs to be generated based on the nesting.  The pattern I use is that the child generates its own uniqueId by calling a function in context to get the unique id of its parent and incorporating that into its own id.  The immediate parent container provides this function, in order to ensure uniqueness the container looks for and calls this function from it's own context in order to incorporate its own parent container's uniqueId in its id.

Perhaps I'm missing something but, with the proposed new API I cannot see how the child can dynamically obtain a reference to the context it's parent provides.  How can this link be made if we do not know until run-time which context provider a child should consume?

**Comment by jamesplease** [comment]
**Nesting**

You could pass the consumer as a prop to the child. This supports the situation where you don’t know which context provider the child should consume until run-time.

```jsx
// Parent.jsx
return (
  <MyChild contextConsumer={MyContext.Consumer}/>
);
```

**Overrides**

One idea is to take a value from a Context and then make a new context. Paired with the above pattern, this should support both of your use cases.

```jsx
<ContextOne.Consumer>
  {value => {
    <ContextTwo.Provider value={`${value}-please`}>
      <Stuff/>
    </ContextTwo.Provider>
  }}
</ContextOne.Consumer>
```

**Comment by gaearon** [comment]
I’m struggling to understand what you’re asking. Can you provide a tiny code example?

**Comment by jackgeek** [comment]
Hi thanks for taking the time to consider my use case.

I have created a minature version of a metadata driven app to illustrate how context is used in my application here: 

[https://codesandbox.io/s/jz5q4o4429](https://codesandbox.io/s/jz5q4o4429)

**Comment by jackgeek** [comment]
Hi guys,

I figured out how to do it.  Thanks again for your time.  

The solution was to nest the Provider inside of a Consumer for the same context.

https://codesandbox.io/s/pkx40pmwxj

```javascript
import React from "react";
import { render } from "react-dom";
import PropTypes from "prop-types";

const styles = {
  fontFamily: "sans-serif",
  textAlign: "center"
};

const ContainerContext = React.createContext(x => x);

class Container extends React.Component {
  _getContainedWithin = name => {
    return `${name} is contained within ${this.props.metadata.name}`;
  };

  render() {
    return (
      <ContainerContext.Consumer>
        {getContainedWithin => (
          <ContainerContext.Provider
            value={name => getContainedWithin(this._getContainedWithin(name))}
          >
            <PagePartBuilder metadata={this.props.metadata.childComponents} />
          </ContainerContext.Provider>
        )}
      </ContainerContext.Consumer>
    );
  }
}

const Widget = (props, context) => (
  <ContainerContext.Consumer>
    {getContainedWithin => <div>{getContainedWithin(props.metadata.name)}</div>}
  </ContainerContext.Consumer>
);

Widget.contextTypes = {
  getContainedWithin: PropTypes.func
};

function PagePartBuilder(props) {
  if (Array.isArray(props.metadata)) {
    return props.metadata.map(metadata => (
      <PagePartBuilder metadata={metadata} />
    ));
  }
  let Component;
  switch (props.metadata.type) {
    case "Container":
      Component = Container;
      break;
    default:
      Component = Widget;
  }
  return <Component metadata={props.metadata} />;
}

// metadata is not known until run-time
const metadata = {
  type: "Container",
  name: "Foo",
  childComponents: [
    {
      type: "Container",
      name: "Bar",
      childComponents: [
        {
          type: "Widget",
          name: "A"
        }
      ]
    },
    {
      type: "Container",
      name: "Baz",
      childComponents: [
        {
          type: "Widget",
          name: "B"
        }
      ]
    },
    {
      type: "Widget",
      name: "C"
    }
  ]
};

const App = () => (
  <div style={styles}>
    <PagePartBuilder metadata={metadata} />
  </div>
);

render(<App />, document.getElementById("root"));

```

**Comment by nanxiaobei** [comment]
https://github.com/nanxiaobei/react-easy-contexts
