### ISSUE TITLE
Negated Boolean Prop Shorthand

### ISSUE THREAD

**Issue by streamich** [reactjs/rfcs#50]
JSX has a shorthand boolean prop notation, which sets prop to `true`.

```jsx
<input disabled />
<Button small primary ghost disabled block>Click me!</Button>
```

But this feature allows to set props only to `true`. What do you think about a shorthand
for setting a prop to `false`? Like, this is my use case:

```jsx
<Markdown !escapeHtml source={/*...*/} />
```

It is useful for components which have props that default to `true`.

**Comment by TrySound** [comment]
@streamich Optional prop is falsy by default. If you want strict comparison add `defaultProps` flag. There's no need in syntax noise.

**Comment by streamich** [comment]
@TrySound 

> Optional prop is falsy by default.

Yes, that's why I wrote:

> It is useful for components which have props that default to `true`.

--- 

Syntax noise is this:

```jsx
<Markdown escapeHtml={false} />
```

This is syntax sugar:

```jsx
<Markdown !escapeHtml />
```

**Comment by TrySound** [comment]
Syntax noise is irregular cases. This syntax covers more cases.
```
<Markdown escapeHtml={false} />
```

Less special syntax means less noise. That's why lisp is the simplest language from point of syntax.

**Comment by kingdaro** [comment]
Would be a more fitting discussion for the JSX repo instead https://github.com/facebook/jsx

**Comment by krotovic** [comment]
I agree with @TrySound.

And when you have that prop default to truthy then it is good practice to be explicit. In that way you visually distinct the default behavior from that special case. When you have the existing syntax you see in instant the meaning but in your case it's easy to overlook the `!` mark.

**Comment by AugustinLF** [comment]
I'm not a huge fan of syntaxic sugar. When teaching React (and JSX) to beginners, I've observed that the boolean shorthand syntax was already in itself confusing. It's the same thing for the string syntax (`prop="value"` instead of `prop={"value"}`).

So I would abstain from adding more syntax for non necessary things.

**Comment by gaearon** [comment]
https://github.com/facebook/jsx would be the better place to file this proposal, though I agree it's very unlikely we'd do it.
