### ISSUE TITLE
Foreign renderer

### ISSUE THREAD

**Issue by intellild** [reactjs/rfcs#57]
```jsx
ReactDOM.render(
  <div>
    {/* For example: */}
    {ReactCanvas.render(/* ... */)}
    {ReactDOM.render(/* ... */)}
  </div>
)
```
What it solves?
Contents that need renderers other than DOM, such as Charts.

**Comment by threepointone** [comment]
We already do something like this with React-art, you could have a look at its implementation (or use it directly).
