### ISSUE TITLE
[Hooks] Passing the Context only to useContext

### ISSUE THREAD

**Issue by FredyC** [reactjs/rfcs#72]
One question that came up [in DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30036#discussion_r228669345).

```ts
const { Consumer } = React.createContext(50);

function Example() {
  const context = useContext(Consumer); // Passing Consumer only
  return <p>Value: {context}</p>;
}
```

This will cause the warning

> Calling useContext(Context.Consumer) is not supported, may cause bugs, and will be removed in a future major release. Did you mean to call useContext(Context) instead?

Why is that? I mean if this works now, why to remove it later? If the full context object will be required it kinda makes 3rd party libraries more confusing as they usually want to wrap the `Provider`. Is it expected that library authors will export custom hook? Feels like a strange limitation.

**Comment by AlexGalays** [comment]
This would be very useful.

**Comment by Aprillion** [comment]
Is there a technical problem with the current model for 3rd party libraries or just non-intuitive how to create custom hooks? IMHO, `useContext(Consumer)` might be prone to bugs when using multiple contexts... The library code can export the consumer as a custom Hook:
```
const MyContext = React.createContext()
export const MyProvider = MyContext.Provider
export const useMyConsumer = () => useContext(MyContext)
```

**Comment by FredyC** [comment]
@Aprillion I agree. I made this issue mostly when I did not know all the consequences. It's true that exporting custom hook giving access to the context from the library is cheap enough. Some libraries might even want to expand that context with additional functionality or expose only public parts of the context.

I am closing this now as I don't longer consider it an issue :)
