### ISSUE TITLE
[Hooks] Alternative state

### ISSUE THREAD

**Issue by pungggi** [reactjs/rfcs#73]
I would prefere this 
Language-level syntax  `state foo = 5;`
rather than `const [foo, setFoo] = useState(5);`

The latter feels so cumbersome.

**Comment by TonyGorez** [comment]
Where is the link with setFoo in `state foo = 5;`?

**Comment by pungggi** [comment]
I imagine this acting like a proxy, so like setting a normal variable: `foo = 5;` (yes old browsers are excluded here)

think about it, react is not the only framework, that needs do deal with state. Almost every Web App written in Javascript needs state, so why not integrate it in the language? Frameworks can then implement specific logic, whatever 'state' means to Vue, React ...etc..

**Comment by milesj** [comment]
Are you suggesting new *syntax* to JS itself with the `state` symbol? This isn't the correct place for this.
