### ISSUE TITLE
useAdopt

### ISSUE THREAD

**Issue by streamich** [reactjs/rfcs#75]
I am wondering if the below described behaviour is already possible to achieve with existing React hooks, if yes, please tell me how.

I thinking it would be nice to have a React hook&mdash;say `useAdopt`&mdash;that would render a React element into the current component.

For example, here could be a use case for [`useAudio`](https://github.com/streamich/react-use/blob/master/docs/useAudio.md) hook:

```jsx
const Comp = () => {
  const [element, state, actions] = useAudio();

  return (
    <>
       {element}
       <div>Audio is playing: {state.isPlaying}</div>
    </>
  );
};
```

*(Above `element` renders `<audio>` tag.)*

Instead above example could be rewritten using `useAdopt` hook:

```jsx
const Comp = () => {
  const [element, state, actions] = useAudio();
  useAdopt(element);

  return (
     <div>Audio is playing: {state.isPlaying}</div>
  );
};
```

So, basically all that `useAdopt` does is inserts a fragment before the returned JSX of the component. *(Obviously, `useAdopt` could have been used internally in `useAudio` itself, so that user does not have to use it.)*

This could be useful to convert numerous render-prop components we have to hooks. For example, let's say you have an `<Animation/>` FaCC.

```jsx
const Comp = () => {
  return (
     <Animation from={0} to={100}>{(value) =>
       <Ball x={value} />
     }</Animation>
  );
};
```

Using `useAdopt` hook this FaCC could be converted to a hook:

```jsx
const useAnimation = (from, to) => {
  const [value, set] = useState(from);
  useAdopt(<Animation from={from} to={to}>{(value) => {
    set(value);
    return null;
  }}</Animation>);
  return value;
};

const Comp = () => {
  const value = useAnimation(0, 100):
  return (
     <Ball x={value} />
  );
};
```

Then in user-space we can create `useFaCC` for example:

```jsx
const useFaCC = (element) => {
  const [value, set] = useState();
  const el = React.cloneElement(element, {
    children: (value) => {
      set(value);
      return null;
    }
  });
  useAdopt(el);
  return value;
};

const Comp = () => {
  const value = useFaCC(<Animation from={0} to={100} />):
  return (
     <Ball x={value} />
  );
};
```

**Comment by streamich** [comment]
For now I created this [`useAdopt`](https://github.com/streamich/react-use/blob/master/docs/useAdopt.md) workaround, which requires you to render a fragment manually.

**Comment by TonyGorez** [comment]
Hey @streamich, How are you ? 
Can you make work in a CodeSandBox for testing :) ? Or an other stuff like that ?

**Comment by gaearon** [comment]
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.
