### ISSUE TITLE
[Hooks] useSuspense

### ISSUE THREAD

**Issue by cloudever** [reactjs/rfcs#79]
In some cases, a Suspense must be declared in a parent component, that makes a more division of component tree
```js
function SuspensibleDataSourceContainer() {
   return (
     <React.Suspense fallback="loading">
       <DataSourceContainer />
     </React.Suspense>
   )
}
```

Maybe add `useSuspense` that would do the same thing as catch a thrown promise?

```js
function DataSourceContainer() {
   // declare before
   useSuspense(FallbackComponent, maxDuration);
   // call resource fetcher
   const data = resource.read();

   return <DataViewComponent {...data} />
}
```

This way one intermediary component `SuspensibleDataSourceContainer` might be avoided.

**Comment by PascalSenn** [comment]
Well... 
That'd be very, very. very magic. 
The only way that useSuspense would work is, that it would wrap the current functional component with a suspense component. This would be some kind of HOC effect. 
Imagine this scenario: 
```
/// Pseudocode
Parent render()  => 
      DataSourceContainer render() =>  // at this point the interpreter doesn't know anything about useSuspense
            useSuspense(...) => 
                 // at this point you are inside the render method of DataSourceContainer and now
                 // you would have to wrap the component you are currently rendering
                 // with a Suspense Component
```
I'm not saying there is no way to build this. But probably not worth the effort.

The only way the interpreter knows about useSuspense would be that it return a callback. 
But that would literally be a HOC
```javascript
function DataSourceContainer() {
  var wrapper =  useSuspense(FallbackComponent, maxDuration);
   // call resource fetcher
   const data = resource.read();

   return wrapper(<DataViewComponent {...data} />);
}

// same as 
function DataSourceContainer() {
   
   
   // call resource fetcher
   const data = resource.read();

   return useSuspense(FallbackComponent, maxDuration)(<DataViewComponent {...data} />);
}
```

Even if you put some suspense sugar into the error boundaries, you still face the problem that they cannot return a component directly.

**Comment by marlonmleite** [comment]
I agree with @PascalSenn, this would really look some kind of HOC effect.

**Comment by cloudever** [comment]
@PascalSenn looks effortable
