### ISSUE TITLE
[Hooks] getState 

### ISSUE THREAD

**Issue by PascalSenn** [reactjs/rfcs#81]
I'm pretty hyped about hooks already. I like concept as it respects SOLID better than the current implementation. 

It would be great to have a getState method on hooks though. 

**Syntax**
```js
const [value, setValue, getValue] = useState(0);
```

**But, what for**
I'm not sure if this is an edgecase and even worth bothering. 
But there are a few cases you'd like to have a getState method that does not mutate. 

*1. Objects / Browser APIs*
Imagine you want to create a class that need a handler injected by the constructor. 
Let's take ResizeObserver as an example. 
```js
const [value, setValue] = useState(0);
new ResizeObserver(() =>{ /*This code is executed everytime an observed element resizes*/ 
    doMagic(value)
} );
```
 The resizeObserver could be stored in the state and effects could be used to observe and unobserve DOM elements.  The problem is that the handler you inject does not know about state updates. The variable still points to the same value in the memory. 

Well, there's always a workaround. You could store an object in the state and then pass the reference into the handler and always get the current value but this just doesn't feels right. 

```js
 const [width, setWidth] = useState(0);
  const [height, setHeight] = useState(0);
  const [shared] = useState({
    width,
    height
  });
  shared.width = width;
  shared.height = height;

  function resizeHandler(entries) {
       // here you always get the current values with shared.width and shared.height
  }
```

Here's an implementation of an resizeObserver hook.
https://codesandbox.io/s/l9q7ln6lm7

*2. Event Handlers*
With `React.memo()` we get the ability to reduce unnecessary re renders. Still a problem are event handlers. 

```js
   function Sample(props) {
      const [count, setCount] = useState(0);
       
       const increment = (e) => setCount(count+1);
       return <HeavySubComponent onClick={increment} />
  }
``` 

In this case the HeavySubComponent gets rerendered always. Event though, only a event handler changed.

Here's an example:
https://codesandbox.io/s/1z45wml3w7

With memorizing the method we could solve this problem.

```js
  function useEventHandler(handler) {
     const memoizedHandler = memoizeOne((...args) => handler(...args));
      const [handler, setHandler] = useState(memoizedHandler );
  }

   function Sample(props) {
      const [count, setCount] = useState(0);
       
       const increment = (e) => setCount(count+1);
       return <HeavySubComponent onClick={increment} />
  }
``` 
here's an example. I mocked the behavior of getState.
https://codesandbox.io/s/2zp01w0x2p

**Comment by streamich** [comment]
I had similar problems and wrote `useGetSet` hook that exposes `get()` method.

- https://github.com/streamich/react-use/blob/master/docs/useGetSet.md

Hope it helps.

**Comment by PascalSenn** [comment]
@streamich 
I know that there are ways around it. You could just create a really simple hook to get a getter.

```js
function useStateWithGetter(initialState) {
  const [value, setValue] = useState(initialState);
  const [s] = useState({});
  const [getValue] = useState(() => () => s.value);
  s.value = value;
  return [value, setValue, getValue];
}
```
https://codesandbox.io/s/771m4p5n6

It just feels like an unnecessary pain.

**Comment by TrySound** [comment]
@PascalSenn `useRef` would be better for mutable data.

**Comment by asafigan** [comment]
This would also be useful for optimizations. Currently any call to setState will cause a rerender. It would be nice to be able to check the current state in a hook or event handler to see if the state even needs to be updated. This might be better handled in a different way like being able to control when state triggers rerender with an extra argument to useState or something like that.

On another note: should we comment on optimizations or just api changes in the rfcs? Currently multiple sync state changes cause multiple renders with each render only getting one change at a time. This seems a bit inefficient.

**Comment by Aprillion** [comment]
@PascalSenn if there is a need to re-render `<HeavySubComponent />` only when `count` changes, there is an official React way™ available:
`<HeavySubComponent key={count} />`

IMHO it'd be more clean to use a global state management library to be able to read some share-able state outside of React, but what about following pattern, would it be a "good" solution even without additional features? (not tested yet)
```
const [value, setValue] = useState()
useEffect(() => {
  const getValue = () => value
  const observer = new ResizeObserver(() => { getValue });
  return observer.unsubscribe
}, [])
```

**Comment by asafigan** [comment]
The problem is that setValue doesn't update the value it replaces it. So in your code, getValue will only return the original value and will not update when setValue is called.
