### ISSUE TITLE
[Hooks] useEffect infinite loop

### ISSUE THREAD

**Issue by Aprillion** [reactjs/rfcs#86]
I managed to create an infinite loop with `useEffect` when synchronizing URL with a local `route` state when preparing an example for a workshop.

Full (fixed) code is on https://github.com/msd-code-academy/react-workshop/blob/76d381db8f44ec2a89ed96b22035552e70ef4bf5/00-props-state/search-example/src/App.js , the main part is:

```JS
const getHash = () => window.decodeURI(window.location.hash.substr(1))

const App = () => {
  const [route, setRoute] = useState(getHash())

  useEffect(() => {
    window.location.hash = route
  }, [route])

  useEffect(() => {
    window.onhashchange = () => setRoute(getHash())
    return () => window.onhashchange = undefined
  }, [])
  ...
```

I did not save the version with an infinite loop (sorry, I had a deadline), but my browser became completely unresponsive and I was not able to close the tab or switch to other tabs, only to kill whole browser (and send a crash report to Firefox and then the restored session was loaded with old code so I had to kill it again without restoring the session).

Maybe there is a safer pattern for 2-way synchronization of internal React state with external resources (feel free to comment), but I wonder if it would be possible to *somehow detect an infinite loop and prevent a never ending re-rendering*, or some other way to allow the browser to be responsive for tab closing / hot reloading of a fixed version?

Perhaps debouncing the `useEffect` or `setStateX` to 10ms would help, but I have no idea about wider implications (e.g. 60fps animations), nor how often it was actually called (no dev tools in the unresponsive browser)...

**Edit**: I was unable to reproduce with the following simplified version (the page does not freeze), must be something about `window.location` I guess:
```JS
  const [count, setCount] = React.useState(0)
  React.useEffect(() => setCount(count + 1), [count])
```

**Comment by Jessidhia** [comment]
This _should_ be fixed on current master (if the reducer's result is `===` the previous result, the dispatcher won't trigger an update)
