### ISSUE TITLE
[Hooks] useSharedRef(Symbol)

### ISSUE THREAD

**Issue by xaviergonz** [reactjs/rfcs#88]
Since hooks are extremely isolated it is impossible to make some hooks act differently depending on if another hook has been previously used on the same component or not.

While this might be easy to pull off when the userland is completely controlled (for example by getting a value from hook 1 and passing it to hook 2) it becomes impossible when it is not.

Imagine this use case (1):
- A library offers two hooks
- They can be used separately, but not together
- There's no way for the hooks to know when this happens

Another use case (2):
- A hook is supposed to be used only once per component
- How?

A way to be able to do this could be using a
```const data = useSharedRef(Symbol)```
Where the data only is shared *when inside the same component*.

Use case 1:
```
const hook1UsedSymbol= new Symbol();
const hook2UsedSymbol= new Symbol();

function useHook1() {
  const hook1Used = useSharedRef(hook1UsedSymbol);
  const hook2Used = useSharedRef(hook2UsedSymbol);
  useMemo(() => {
    if (hook2Used) {
      throw new Error('hook 1 incompatible with hook 2')
    }
    hook1Used.current = true;
  }, []);
}

function useHook2() {
  const hook1Used = useSharedRef(hook1UsedSymbol);
  const hook2Used = useSharedRef(hook2UsedSymbol);
  useMemo(() => {
    if (hook1Used) {
      throw new Error('hook 2 incompatible with hook 1')
    }
    hook2Used.current = true;
  }, []);
}
```

Use case 2:
```
const hookUsedSymbol= new Symbol();

function useHook() {
  const hookUsed = useSharedRef(hookUsedSymbol);
  useMemo(() => {
    if (hookUsed) {
      throw new Error('hook can only be used once')
    }
    hookUsed.current = true;
  }, []);
}
```

**Comment by xaviergonz** [comment]
another option would be to add a hook such as
`const componentId = useComponentId()` that would return a unique id per component instance

Then the hook above could be implemented by using a `WeakMap<componentInstance, private data>`

**Comment by sebmarkbage** [comment]
Note that one of the design goals of hooks is to be able to inline one component into another seamlessly to avoid the overhead associated with having two separate components. So it's an active goal to try to avoid creating foot-guns that prevent this from being safe.

**Comment by xaviergonz** [comment]
Thanks for the response.
So there are no plans to have a "escape hatch" for this kind of use cases (like there is a escape hatch for useImmutableMethods while it is usually not recommended)?

Note that this idea is basically intra-component, it never expands outside the current component.
E.g. the useSharedRef "reference state" only lives inside the same component, it would never live outside it.

Same would be for useComponentInstanceId.

**Comment by xaviergonz** [comment]
Also, this is more geared towards library creators than end users really, and exactly to prevent them from shooting themselves on the foot.

In mobx-react-lite for example there is a hook that registers a "mutation listener / observer", where registering it more than once only achieves more memory used, some unwanted re-renders and little else, so something like this would allow the library to warn them of such usages in dev mode, but without such hook there's no way to enforce this (AFAIK, maybe I'm missing something).

**Comment by gaearon** [comment]
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.
