### ISSUE TITLE
[Contexts]to control the render of Consumer Component

### ISSUE THREAD

**Issue by MuYunyun** [reactjs/rfcs#95]
In the [Context.Provider](https://reactjs.org/docs/context.html#contextprovider), there is a word as follow:

> All consumers that are descendants of a Provider will re-render whenever the Provider’s value prop changes. The propagation from Provider to its descendant consumers is not subject to the shouldComponentUpdate method.

It says the Consumer Component will be updated when the value in the Provider Component changes. I understand the reason why the `shouldComponentUpdate or PureComponent` not effect in the Consumer Component. In my option, there should still be a method to replace the `shouldComponentUpdate` to control the reRender of the Consumer Component.

**Comment by TrySound** [comment]
There is one in child component

**Comment by MuYunyun** [comment]
```js
class Demo extends React.Component {
  onChange = (e) => {
    this.setState({
      global: {}
    })
  }

  render() {
    <FormContext.Provider value={this.state.global}>
      <FormContext.Consumer>{
        (global => <Input onChange={this.onChange} />) // ①
      }</FormContext.Consumer>
      <FormContext.Consumer>
        (global => <OtherComponent />)
      </FormContext.Consumer>
    </FormContext.Provider>
  }
}

class OtherComponent extends React.PureComponent {
  render() { // ②
    <Input />
  }
}
```

for example, when I change the value in ①, I only want the ① to rerender, and the ② not render(PureComponent), but now it seems there is no method to achieve the purpose.Tomorrow I'll try to validate.

**Comment by MuYunyun** [comment]
sorry, it's my fault. I pass a new Object to the PureComponent to make it render every time.
