### ISSUE TITLE
[Hooks] useContext tuple

### ISSUE THREAD

**Issue by thysultan** [reactjs/rfcs#99]
The single return value from `useContext` leaves much to be desired. Is there any reason that useContext does not return a value/setter tuple in the fashion of `useState`?

This would allow React to provide a guarantee of more granular updates: That is instead of the need to re-render a provider high up in the tree. The consumer component could update the context with only consumer dependencies subscribing to the update.

```js
import {useContext, createContext} from 'React'
import {render} from 'ReactDOM'

const themeContext = createContext('red')

function A (props) {
	const [theme, setTheme] = useContext(themeContext)
	return <button onClick={() => setTheme('blue')}>{theme}</button>
}

function B (props) {
	const [theme, setTheme] = useContext(themeContext)
	return <button onClick={() => setTheme('orange')}>{theme}</button>
}

ReactDOM.render(<div>
	<Fragment><A></A></Fragment>
	<Fragment><Fragment><B></B></Fragment></Fragment>
<div>, container)
```

An example akin to a router could use this to guarantee granular updates to consumers that does not in effect rely on traversing all components within a provider to reach all consumers.

```js
const routerContext = createContext('/')

export function useRouter () {
	const [route, setRoute] = useContext(routerContext)
	
	useEffect(() => {
		window.addEventListener('popstate', () => {
			setRoute(location)
		})
	}, [])

	return route
}

export function Link () {
	return <a onClick={() => window.dispatchEvent(new Event('popstate'))}></a>
}

function routerConsumer ({href, children}) {
	const route = useRouter()
	return route === href ? children : null
}
```

**Comment by jfo84** [comment]
If you read around the RFCs and PRs, you can find some references to the use of two contexts, a state context and an implementation context. If you want to keep it pure, only expose the implementation context and use methods defined there to manipulate state.

Context is purposefully an abstract API IMO. This makes it not so abstract anymore.

**Comment by TrySound** [comment]
This can be easily implemented in user land. Context consumer not always should set value. Out of the box react has all necessary primitives.
```js
const Context = React.createContext([null, () => {}]);

export const Provider = ({ initialValue, children }) => {
  const value = React.useState(initialValue);
  return (
    <Context.Provider value={value}>
      {children}
    </Context.Provider>
  );
};
```

**Comment by thysultan** [comment]
@jfo84 Yes the second example demonstrates this by only returning the context value: `route`, instead of the setter. This is as much an abstract API if not more as what is currently present.

@TrySound That suffers from the same issues that `useContext` and hooks in general is meant to alleviate(the pyramid of doom), in addition to the issue this aims to improve; among which is the in-existence of a way to update consumers without in-evidently also re-rendering all components within the providers subtree.

This is close to the `Context.write` proposal than anything else.

**Comment by illuminist** [comment]
In case of you're missing something: context API is NOT a state manager. Context is only just a way to pass a value to deeper components. Which means you have to combine context with some kind of state manager, eg, useState, useReducer to achieve what you proposed.

**Comment by gaearon** [comment]
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.
